name: Publish package to GitHub Packages
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: write
      packages: write
      deployments: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Installing node and npm'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Create a .npmrc file for the github private repository
        uses: FerLuisxd/create-npmrc@4
        with:
          org_name: '@smashtaps'
          auth_token: '$NODE_AUTH_TOKEN'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Deploy package'
        run: |
          npx ci --ignore-scripts
          npx publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
